### ISSUE TITLE
ToDo - List

### ISSUE THREAD

**Issue by toziegler** [DataManagementLab/dpi_library#18]
- [x] Decrease header size - profit in latency based @LasseThostrup 

- [x] In BufferIterator at header-logic for concurrent Write and Iteration @LasseThostrup 

- [x] In BufferIterator mark segment as reusable @LasseThostrup 

- [x] Add methods for creating a Latency Buffer @toziegler 

1.  Proto Message (Done)
2. Buffer Registration
3. Create Counters 

- [x]  BufferIterator for latency - Inheritance since similarity of existing one? (@toziegler)

1.  Only change is to increment the counter whenever segment is reused

- [x] BufferWriter for latency (@toziegler  & @LasseThostrup)
 
1.  Start with contingent of segments e.g. 100.
2. Write those and then read the counter, which is inc. by the Iterator

- [ ] Differentiate between msg < 64 Byte .e.g. Cacheline or lager (CRC needed)
